/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=retention/wrangler.jsonc --include-runtime=false retention/env.d.ts` (hash: daf4456e584de40cee6f61132047fded)
interface __BaseEnv_Env {
	SENDARC_DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
